### ISSUE TITLE
Installation warnings

### ISSUE THREAD

**Issue by briatte** [joelgombin/Insee2MonetDB#5]
Here's what I get when installing the package:

```
> install_github("joelgombin/Insee2MonetDB")
Downloading GitHub repo joelgombin/Insee2MonetDB@master
from URL https://api.github.com/repos/joelgombin/Insee2MonetDB/zipball/master
Installing Insee2MonetDB
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
Warning in read.dcf(file = tmpf) :
  cannot open compressed file '/var/folders/b4/8mqg2_7107v7269fc9xgj9gw0000gn/T//RtmpYC3LWL/file56912331e577', probable reason 'No such file or directory'
Warning: unable to access index for repository http://dev.monetdb.org/Assets/R/bin/macosx/mavericks/contrib/3.3:
  cannot open the connection
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  124k  100  124k    0     0    98k      0  0:00:01  0:00:01 --:--:--   98k
Installing MonetDB.R
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/b4/8mqg2_7107v7269fc9xgj9gw0000gn/T/RtmpYC3LWL/devtools569120cff9ae/MonetDB.R'  \
  --library='/Users/fr/Library/R/3.3/library' --with-keep.source --install-tests 

* installing *binary* package ‘MonetDB.R’ ...
* DONE (MonetDB.R)
curl: (22) The requested URL returned error: 404 Not Found
Warning in read.dcf(file = tmpf) :
  cannot open compressed file '/var/folders/b4/8mqg2_7107v7269fc9xgj9gw0000gn/T//RtmpYC3LWL/file569160389d66', probable reason 'No such file or directory'
Warning: unable to access index for repository http://dev.monetdb.org/Assets/R/bin/macosx/mavericks/contrib/3.3:
  cannot open the connection
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2247k  100 2247k    0     0   705k      0  0:00:03  0:00:03 --:--:--  705k
Installing MonetDBLite
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/b4/8mqg2_7107v7269fc9xgj9gw0000gn/T/RtmpYC3LWL/devtools569124e5c4e4/MonetDBLite'  \
  --library='/Users/fr/Library/R/3.3/library' --with-keep.source --install-tests 

* installing *binary* package ‘MonetDBLite’ ...
* DONE (MonetDBLite)
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/b4/8mqg2_7107v7269fc9xgj9gw0000gn/T/RtmpYC3LWL/devtools56916da4eb76/joelgombin-Insee2MonetDB-f95a19d'  \
  --library='/Users/fr/Library/R/3.3/library' --with-keep.source --install-tests 

* installing *source* package ‘Insee2MonetDB’ ...
Warning in .write_description(db, file.path(outDir, "DESCRIPTION")) :
  Unknown encoding with non-ASCII data: converting to ASCII
** R
** preparing package for lazy loading
Warning: replacing previous import ‘MonetDB.R::MonetR’ by ‘MonetDBLite::MonetR’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::src_monetdb’ by ‘MonetDBLite::src_monetdb’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monetdb.liststatus’ by ‘MonetDBLite::monetdb.liststatus’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::mc’ by ‘MonetDBLite::mc’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monetdb.server.getpid’ by ‘MonetDBLite::monetdb.server.getpid’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::mdbapply’ by ‘MonetDBLite::mdbapply’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::MonetDB.R’ by ‘MonetDBLite::MonetDB.R’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::dbSendUpdateAsync’ by ‘MonetDBLite::dbSendUpdateAsync’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monetdbd.liststatus’ by ‘MonetDBLite::monetdbd.liststatus’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monetdb.server.start’ by ‘MonetDBLite::monetdb.server.start’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::isIdCurrent’ by ‘MonetDBLite::isIdCurrent’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::dbSendUpdate’ by ‘MonetDBLite::dbSendUpdate’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::dbTransaction’ by ‘MonetDBLite::dbTransaction’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monetdb.server.setup’ by ‘MonetDBLite::monetdb.server.setup’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monetdb.server.stop’ by ‘MonetDBLite::monetdb.server.stop’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::MonetDBR’ by ‘MonetDBLite::MonetDBR’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::RMonetDBLite’ by ‘MonetDBLite::RMonetDBLite’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monetdblite’ by ‘MonetDBLite::monetdblite’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monetdb.server.shutdown’ by ‘MonetDBLite::monetdb.server.shutdown’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::initExtension’ by ‘MonetDBLite::initExtension’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::rmonetdblite’ by ‘MonetDBLite::rmonetdblite’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::MonetDBLite’ by ‘MonetDBLite::MonetDBLite’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monet.read.csv’ by ‘MonetDBLite::monet.read.csv’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::MonetDB’ by ‘MonetDBLite::MonetDB’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monetdb.read.csv’ by ‘MonetDBLite::monetdb.read.csv’ when loading ‘Insee2MonetDB’
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Warning: replacing previous import ‘MonetDB.R::MonetR’ by ‘MonetDBLite::MonetR’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::src_monetdb’ by ‘MonetDBLite::src_monetdb’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monetdb.liststatus’ by ‘MonetDBLite::monetdb.liststatus’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::mc’ by ‘MonetDBLite::mc’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monetdb.server.getpid’ by ‘MonetDBLite::monetdb.server.getpid’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::mdbapply’ by ‘MonetDBLite::mdbapply’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::MonetDB.R’ by ‘MonetDBLite::MonetDB.R’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::dbSendUpdateAsync’ by ‘MonetDBLite::dbSendUpdateAsync’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monetdbd.liststatus’ by ‘MonetDBLite::monetdbd.liststatus’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monetdb.server.start’ by ‘MonetDBLite::monetdb.server.start’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::isIdCurrent’ by ‘MonetDBLite::isIdCurrent’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::dbSendUpdate’ by ‘MonetDBLite::dbSendUpdate’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::dbTransaction’ by ‘MonetDBLite::dbTransaction’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monetdb.server.setup’ by ‘MonetDBLite::monetdb.server.setup’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monetdb.server.stop’ by ‘MonetDBLite::monetdb.server.stop’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::MonetDBR’ by ‘MonetDBLite::MonetDBR’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::RMonetDBLite’ by ‘MonetDBLite::RMonetDBLite’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monetdblite’ by ‘MonetDBLite::monetdblite’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monetdb.server.shutdown’ by ‘MonetDBLite::monetdb.server.shutdown’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::initExtension’ by ‘MonetDBLite::initExtension’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::rmonetdblite’ by ‘MonetDBLite::rmonetdblite’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::MonetDBLite’ by ‘MonetDBLite::MonetDBLite’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monet.read.csv’ by ‘MonetDBLite::monet.read.csv’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::MonetDB’ by ‘MonetDBLite::MonetDB’ when loading ‘Insee2MonetDB’
Warning: replacing previous import ‘MonetDB.R::monetdb.read.csv’ by ‘MonetDBLite::monetdb.read.csv’ when loading ‘Insee2MonetDB’
* DONE (Insee2MonetDB)
```

The package still installs fine, and the example works, although with warnings again:

```
> tbl_mobsco_2012 <- Insee2MonetDB("http://telechargement.insee.fr/fichiersdetail/RP2012/txt/RP2012_MOBSCO_txt.zip")
trying URL 'http://telechargement.insee.fr/fichiersdetail/RP2012/txt/RP2012_MOBSCO_txt.zip'
Content type 'unknown' length 38542419 bytes (36.8 MB)
==================================================
downloaded 36.8 MB

arguments 'minimized' and 'invisible' are for Windows only
Source:   query [?? x 22]
Database: MonetDB  ()

   commune   arm dcetue dcetuf agerev10   csm derou  dipl iletud iletuu ineem inpsm   ipondi  lprm metrodom
     <chr> <chr>  <chr>  <chr>    <chr> <chr> <chr> <chr>  <chr>  <chr> <chr> <chr>    <dbl> <chr>    <chr>
1    01001 ZZZZZ  99999  01001       05     3     Z    ZZ      1      1     0     2 3.984615     3        M
2    01001 ZZZZZ  99999  01001       06     3     Z    ZZ      1      1     0     2 3.984615     3        M
3    01001 ZZZZZ  99999  01001       06     4     Z    ZZ      1      1     0     2 3.984615     3        M
4    01001 ZZZZZ  99999  01001       06     4     Z    ZZ      1      1     2     4 3.984615     3        M
5    01001 ZZZZZ  99999  01001       06     1     Z    ZZ      1      1     1     3 3.984615     3        M
6    01001 ZZZZZ  99999  01001       04     3     Z    ZZ      1      1     0     1 3.984615     3        M
7    01001 ZZZZZ  99999  01001       06     4     Z    ZZ      1      1     0     2 3.984615     3        M
8    01001 ZZZZZ  99999  01001       06     5     Z    ZZ      1      1     1     2 3.984615     3        M
9    01001 ZZZZZ  99999  01001       06     5     Z    ZZ      1      1     0     2 3.984615     3        M
10   01001 ZZZZZ  99999  01001       11     4     Z    ZZ      1      1     0     2 3.984615     3        M
# ... with more rows, and 7 more variables: nperr <chr>, region <chr>, regionetud <chr>, sexe <chr>,
#   stocd <chr>, typmr <chr>, voit <chr>
Warning: closing unused connection 3 (/var/folders/b4/8mqg2_7107v7269fc9xgj9gw0000gn/T//RtmpYC3LWL/FD_MOBSCO_2012.txt)
```

**Comment by joelgombin** [comment]
I think this should have been fixed by 8fed1465f5afeae3596cf31707ebca4126ed7e6c, would you mind testing again?
Regarding the last warning, I think it's nothing important, but I'll try to remove it.

**Comment by briatte** [comment]
I still get one 404 during install, but that does not seem to have everything working afterwards:

```
> install_github("joelgombin/Insee2MonetDB")
Downloading GitHub repo joelgombin/Insee2MonetDB@master
from URL https://api.github.com/repos/joelgombin/Insee2MonetDB/zipball/master
Installing Insee2MonetDB
curl: (22) The requested URL returned error: 404 Not Found
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/b4/8mqg2_7107v7269fc9xgj9gw0000gn/T/RtmpFVITXj/devtoolsb22b5fa2f1f9/joelgombin-Insee2MonetDB-93b4179'  \
  --library='/Users/fr/Library/R/3.3/library' --with-keep.source --install-tests 

* installing *source* package ‘Insee2MonetDB’ ...
Warning in .write_description(db, file.path(outDir, "DESCRIPTION")) :
  Unknown encoding with non-ASCII data: converting to ASCII
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (Insee2MonetDB)
> library(Insee2MonetDB)
> ?Insee2MonetDB
> tbl_mobsco_2012 <- Insee2MonetDB("http://telechargement.insee.fr/fichiersdetail/RP2012/txt/RP2012_MOBSCO_txt.zip")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 36.7M  100 36.7M    0     0  3790k      0  0:00:09  0:00:09 --:--:-- 4107k
arguments 'minimized' and 'invisible' are for Windows only
Source:   query [?? x 22]
Database: MonetDBLite 0.3.1 (/Users/fr/MonetDB)

Warning: closing unused connection 3 (/var/folders/b4/8mqg2_7107v7269fc9xgj9gw0000gn/T//RtmphwsM2f/FD_MOBSCO_2012.txt)
   commune   arm dcetue dcetuf agerev10   csm derou  dipl iletud iletuu ineem inpsm   ipondi  lprm metrodom
     <chr> <chr>  <chr>  <chr>    <chr> <chr> <chr> <chr>  <chr>  <chr> <chr> <chr>    <dbl> <chr>    <chr>
1    01001 ZZZZZ  99999  01001       05     3     Z    ZZ      1      1     0     2 3.984615     3        M
2    01001 ZZZZZ  99999  01001       06     3     Z    ZZ      1      1     0     2 3.984615     3        M
3    01001 ZZZZZ  99999  01001       06     4     Z    ZZ      1      1     0     2 3.984615     3        M
4    01001 ZZZZZ  99999  01001       06     4     Z    ZZ      1      1     2     4 3.984615     3        M
5    01001 ZZZZZ  99999  01001       06     1     Z    ZZ      1      1     1     3 3.984615     3        M
6    01001 ZZZZZ  99999  01001       04     3     Z    ZZ      1      1     0     1 3.984615     3        M
7    01001 ZZZZZ  99999  01001       06     4     Z    ZZ      1      1     0     2 3.984615     3        M
8    01001 ZZZZZ  99999  01001       06     5     Z    ZZ      1      1     1     2 3.984615     3        M
9    01001 ZZZZZ  99999  01001       06     5     Z    ZZ      1      1     0     2 3.984615     3        M
10   01001 ZZZZZ  99999  01001       11     4     Z    ZZ      1      1     0     2 3.984615     3        M
# ... with more rows, and 7 more variables: nperr <chr>, region <chr>, regionetud <chr>, sexe <chr>,
#   stocd <chr>, typmr <chr>, voit <chr>
> 
> 
```
